config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'
  resources :blogs do
    resources :likes, only: [:create, :destroy] 
  end
  resources :comments
  
  resources :users
  resources :boxs
  resource :rankings, only: [:index]
  get '/ranking', to: 'rankings#index'
  root 'blogs#index'
end

app/models/blog.rb
# == Schema Information
#
# Table name: blogs
#
#  id                  :bigint           not null, primary key
#  body(本文)          :text(65535)      not null
#  deleted_at          :string(255)
#  impressions_count   :integer          default(0)
#  title(タイトル)     :string(255)      not null
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  user_id             :integer
#
class Blog < ApplicationRecord
    validates :title, presence: true, length: { minimum: 1, maximum: 50}
    validates :body, presence: true, length: { minimum:10, maximum: 5000 }
    belongs_to  :user
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    # ページカウント
    is_impressionable counter_cache: true
    
    # 論理削除
    acts_as_paranoid
    
    # 検索機能
    scope :search, ->(params) do
      scope = self
      scope = scope.search_by_title(params[:search_title]) if params[:search_title].present?
      scope = scope.search_by_created_at(params[:search_created_at]) if params[:search_created_at].present?
      scope
    end
    
    scope :search_by_title, -> (value) do
      where("`title` LIKE ?", "%#{value}%")
    end

    scope :search_by_created_at, -> (value) do
      where("DATE(`created_at`) = ?", value.to_date)
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]
  before_action :no_user, only: %i[ new edit update destroy ]
  # GET /blogs or /blogs.json
  def index
    # 記事一覧
    params.keys.each { |x| params.delete x } if params[:clear].present?
    params[:search_created_at] = created_at_params
    @blogs = Blog.search(params).order(created_at: :desc)
    @blogs = @blogs.page(params[:page]).per(7)
  end
  # GET /blogs/1 or /blogs/1.json
  def show
    @blog = Blog.find(params[:id])
    @like = Like.new
    impressionist(@blog, nil, :unique => [:session_hash])
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  def edit

    #投稿者とログインユーザが一致しているか
    if current_user != nil && @blog.user_id == current_user.id
    else
      redirect_to "/blogs", notice: "投稿したユーザでないので編集できません"
    end
  end

  # blog /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    if current_user != nil && @blog.user_id == current_user.id
      @blog.destroy
      respond_to do |format|
        format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
        format.json { head :no_content }
      end
    else
      redirect_to  "/blogs", notice: "投稿したユーザでないので削除できません"
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find_by(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
    # titleとbodyを受け取る
    params.fetch(:blog, {}).permit(:title, :body)
    end

    def created_at_params
      return if params["search_created_at(1i)"].blank? || params["search_created_at(2i)"].blank? || params["search_created_at(3i)"].blank?
      Date.new(
        params["search_created_at(1i)"].to_i,
        params["search_created_at(2i)"].to_i,
        params["search_created_at(3i)"].to_i
      )
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blogs_link.html.erb
<!-- 一覧ページ -->
<% if current_user != nil && request.path == root_path %>
  <%= link_to t('new_blog'), new_blog_path, class: "btn btn-primary" %>
<% end %>

app/views/blogs/_edit_link.html.erb
<!-- 一覧ページ -->
<%= link_to t('back'), root_path, class: "btn btn-primary" %>

app/views/blogs/_form.html.erb
<%= render 'blogs/user' %>
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>
      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="text-center">
  <!-- タイトルを入力するinputタグを表示 -->
  <label for="blog_title"></label><%= form.text_field :title ,id: "title",placeholder: "タイトル" %>
  <!-- 本文入力するtextareタグを表示 -->
  <label for="blog_body"></label><%= form.text_area :body, id: "input-text", rows: 5 ,placeholder: "本文"%>
  </div>
  <div class ="text-right">
    <p id="counter"></p>
  </div>
  <div class="actions">
    <%= form.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/blogs/_login.html.erb
<!-- ユーザがnilなら表示 -->
<div class="text-right">
    <% if current_user == nil %>
        <!-- ログイン -->
        <%= button_to "ログイン", { controller: 'sessions', action: 'new' }, { method: :get, class: "btn btn-primary" } %>
        <!-- 新規登録 -->
        <%= button_to "新規登録", { controller: 'users', action: 'new' }, { method: :get, class: "btn btn-primary" } %>
    <% else %>
        <%= button_to t('logout'), logout_path, { method: :delete, class: "btn btn-primary" } %>
    <% end %>
</div>

app/views/blogs/_new_link.html.erb
<div class="back">
    <%= link_to t('back'), root_path, class: "btn btn-primary" %>
</div>

app/views/blogs/_show_link.html.erb
<%= link_to t('edit'), edit_blog_path(@blog), class: "btn btn-primary" %>
<%= link_to t('back'), root_path, class: "btn btn-primary" %>

app/views/blogs/_user.html.erb
<!-- ユーザがnilなら表示 -->
<% if current_user != nil %>
  <!-- ログインユーザ -->
    現在ログイン中のユーザ：<strong><%=current_user.name %></strong>
<% end %>

app/views/blogs/edit.html.erb
<h1>記事編集</h1>
<%= render 'form', blog: @blog %>
<%= render 'blogs/edit_link' %>
<%= javascript_include_tag "count.js" %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>
<h1>ブログ一覧</h1>
<%= render 'blogs/user' %>  
<%= render 'blogs/login' %>

<!-- 検索の追加 -->
<div class="form">
<%= form_with(path: :blogs_path, local: true, method: :get) do |form| %>
  <%= form.text_field :search_title, value: params[:search_title],placeholder: "タイトル検索" %>
<% end %>
<%= javascript_include_tag "search.js" %>
<%= link_to t('ranking'), ranking_path, class: "btn btn-primary" %>
<%= link_to "復元", boxs_path, class: "btn btn-primary" %>
</div>
<table class="table"> 
  <thead>
    <tr>
      <th>タイトル</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody id="blogs">
    <% @blogs.each do |blog| %>
      <tr>
        <!-- タイトルを追加 -->
        <td><%= blog.title %></td>
        <td><%= link_to t('show'), blog ,class: "btn btn-primary"%></td>
        <td><%= link_to t('edit'), edit_blog_path(blog),class: "btn btn-primary" %></td>
        <td><%= link_to t('destroy'), blog, class: "btn btn-primary", method: :delete ,data: {confirm: "削除しますか？"}%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @blogs %>
<%= render 'blogs/blogs_link' %>

app/views/blogs/new.html.erb
<h1>新規作成</h1>
<%= render 'form', blog: @blog %>
<%= render 'blogs/new_link' %>
<%= javascript_include_tag "count.js" %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>
<%= render 'blogs/user' %>
<%= render 'blogs/login' %>
<!-- 閲覧数 -->
<div class="text-right">
<strong>閲覧数:
<%= @blog.impressions_count %>
</strong>
</div>
<!-- h1タグでタイトルを表示 -->
<h1><%= @blog.title %></h1>
<!-- 本文を表示 -->
  <%= simple_format(@blog.body) %>
<!-- ログインユーザがnilならいいねを非表示にする -->
<% if current_user != nil %>
  <!-- いいねの表示 -->
  <% if current_user.already_liked?(@blog) %>
    <%= button_to 'いいねを取り消す', blog_like_path(@blog), class: 'btn btn-success',method: :delete, remote: true %>
  <% else %>
    <%= button_to 'いいね', blog_likes_path(@blog),class: 'btn btn-success', remote: true %>
  <% end %>
<% end %>
<div class=text-right>
  <p>いいね数：<%= @blog.likes.count %></p>
</div>


<!-- コメント -->
<%= tag.div id: :comments_area do %>
  <%= render partial: "comments/index", locals: { comments: @blog.comments } %>
<% end %>

<!-- ログインユーザがnilならコメント投稿を非表示にする -->
<% if current_user != nil %>
  <!-- コメント投稿 -->
  <%= tag.div id: :comment_form do %>
    <%= render partial: "comments/form", locals: { comment: @blog.comments.build } %>
  <% end %>
<% end %>



<%= render 'blogs/show_link' %>